name: Run Python Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python version
        run: python --version

      - name: Show project structure
        run: ls -R

      - name: Check if src/main.py exists
        run: |
          if [ ! -f "src/main.py" ]; then
            echo "‚ùå src/main.py not found"
            exit 1
          fi

      - name: Run main script
        run: python src/main.py

      - name: Upload blocked domains as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blocked-domains-output
          path: blocked_domains.txt
