name: Run Python Project

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python version
        run: python --version

      - name: Show project structure
        run: ls -R

      - name: Check if main.py exists
        run: |
          if [ ! -f "main.py" ]; then
            echo "‚ùå main.py not found in root directory"
            exit 1
          fi

      - name: Run main script
        run: python main.py
